name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlite3:
        image: kevinliao/sqlite3:latest
        options: >-
          --health-cmd "sqlite3 :memory: 'select 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Setup database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
        env:
          RAILS_ENV: test

      - name: Run tests
        run: bundle exec rails test
        env:
          RAILS_ENV: test

      - name: Run linting
        run: bundle exec standardrb

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman -q -z
        continue-on-error: true

      - name: Run Bundler Audit
        run: bundle exec bundler-audit check --update
        continue-on-error: true
